### ISSUE TITLE
Production modules have old firmware

### ISSUE THREAD

**Issue by johnnyman727** [tessel/ambient-attx4#15]
The old firmware makes the module mess up the SPI MISO line when other SPI based modules try to use it.

We need to write a JavaScript based ISP to update the modules with the most recent firmware.

**Comment by rayfranco** [comment]
I'm still having this issue.

**Comment by johnnyman727** [comment]
@rayfranco is your module not automatically updating its firmware? Can you paste the output here?

**Comment by rayfranco** [comment]
@johnnyman727 I've manually updated here is what I've got: `INFO Firmware Build: 0.1.26`

**Comment by johnnyman727** [comment]
@rayfranco, to be clear there are two microcontrollers at play, each with their own firmware versions. The Tessel has a microcontroller which will have a firmware version like the one you've pasted above (which is up to date as of the time of this comment). The Ambient Module has its own microcontroller with firmware that needs to be up to date. When you run any code using the Ambient Module, it has the capacity to check the firmware version it's microcontroller and update if it's old. 

If you are running Ambient code and it's not reporting that it's updating the module then the firmware is not old.

Can you elucidate on the setup you have, the code you're running, and the issue that you're experiencing? It might be a factor not related to the firmware on the Ambient Module.

**Comment by rayfranco** [comment]
@johnnyman727 I'm trying to find a way to check the firmware on the Ambiant module. The code is [located here](https://github.com/rayfranco/tessel-beograd/tree/master/taggle)

**Comment by johnnyman727** [comment]
@rayfranco It should automatically update itself but if you think it's not up to date, you can run `tessel run debug/update.js` from within the Ambient node module.

**Comment by rayfranco** [comment]
I've updated and still having the same bug. I can't figure out what I'm doing wrong. Code is pretty basic actually.

**Comment by johnnyman727** [comment]
@rayfranco I looked at your code and I think the issue isn't related to the Ambient firmware.

It looks like you're using the Audio module. In order to record data or play data, the firmware has to gain a lock on the communication bus that the Ambient also uses to communicate with Tessel. In theory, they shouldn't collide because only one element can use the SPI bus while it has a lock. 

I'm not sure exactly what the issue is, but I think it probably stems from that implementation detail. Can you be more specific about how your code is failing?

**Comment by rayfranco** [comment]
Exactly how it is described here. The sound is chunky. I tried to play it outside of the event emitted by the Ambient module and it is playing well. I tried to delay the play with a setTimeout but same thing happen. It went a little bit better by decreasing mp3 quality encoding, but it is still chunky.

**Comment by johnnyman727** [comment]
@rayfranco, can you try calling `clearSoundTrigger` after it's been fired to ensure the module doesn't try to update the Tessel with more sound triggers?

**Comment by rayfranco** [comment]
@johnnyman727 I'm already doing this [here](https://github.com/rayfranco/tessel-beograd/blob/master/taggle/src/Ambiant.js#L43). I'm out of solutions. No way to wait (and know when) the ambiant module release its lock on the communication bus before using the conflicting audio module?

**Comment by johnnyman727** [comment]
@rayfranco the ambient module should already be waiting for the audio module to release the spi lock and vice versa. I'll get a chance to debug this in more depth tomorrow.

**Comment by johnnyman727** [comment]
I spent a couple of hours debugging this today and unfortunately didn't make a ton of progress. What I did discover is that [simply adding an IRQ to the ambient module](https://github.com/tessel/attiny-common/blob/master/lib/index.js#L218) seems to interrupt the audio stream when it is played in the future. I don't have a hypothesis how the two interactions are related yet.
