### ISSUE TITLE
Unable to update firmware: Programming confirmation not received

### ISSUE THREAD

**Issue by rwaldron** [tessel/ambient-attx4#52]
I posted this on a closed PR, just going to c/p it here: 

@johnnyman727 I've been trying to get my ambient module updated for hours and it just won't work, any ideas? When I look at the files that get deployed, everything is there, but regardless: 

```
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Building project.
INFO Writing project to RAM on bishop (42.496 kB)...
INFO Deployed.
INFO Running index.js...
Old module firmware detected. Updating...
[Error: Unable to update firmware: Programming confirmation not received.]
```

**Comment by johnnyman727** [comment]
@rwaldron just want to check - are you running the latest released version of the ambient module (or this repo on master)?

**Comment by rwaldron** [comment]
I did `npm install ...`

**Comment by johnnyman727** [comment]
Ok and it did install `0.2.8`? Can you run `npm ls` in your project so I can also see the deps versions?

**Comment by rwaldron** [comment]
```
$ npm install ambient-attx4
spi@0.0.0 /Users/rwaldron/robotz/spi
└── ambient-attx4@0.2.8  extraneous
```

**Comment by johnnyman727** [comment]
Damn, I really thought I fixed this issue. I'll have to experiment a little tonight but it's difficult to reproduce.

**Comment by rwaldron** [comment]
No rush, I just hit it in the process of zoning in on a massive SPI issue that you're going to love ;)

**Comment by johnnyman727** [comment]
@rwaldron what was the SPI issue?

**Comment by johnnyman727** [comment]
I have not been able to reproduce this with the one ambient module that I have with me.

I'll try another 5 or so when I get back to the states on Sunday and report my results.

@rwaldron if you have a logic analyzer and could capture a trace of what's happening, that would be 💯  super useful

**Comment by johnnyman727** [comment]
I tried to reproduce this on 10 different ambient modules today with no luck 😢 . Will try on some IR modules.

**Comment by johnnyman727** [comment]
@rwaldron unless I see any more reports of this issue, I'm going to have to assume your hardware is busted. Sorry!
