### ISSUE TITLE
Thoughts on deprecating the `use` export?

### ISSUE THREAD

**Issue by wyze** [tessel/ambient-attx4#61]
Seems like there is not much functionality there, the hardware check could be moved up into the main `Ambient` function and it can become the main export, `module.exports = Ambient`. Unless there is a good reason for this being split out, I think it could be deprecated and examples updated to reflect using the main export.

`use` export is here, for reference: https://github.com/tessel/ambient-attx4/blob/master/index.js#L375-L380

/cc @rwaldron @johnnyman727

**Comment by johnnyman727** [comment]
I don't have strong feelings about this. My only concern is that this would have to be done across all module repos (and community contributed modules) and it might not be worth the time investment.

The reason we initially designed the API to have a `use` function was just to make it clear that you are expected to assign a module to a port.

**Comment by wyze** [comment]
Seems like a large chore and almost everywhere I looked used this function, so I don't think it is worth the time investment.
